config/routes.rb
Rails.application.routes.draw do
  root 'tags#index'
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :kind, presence: true

  # before_destroy :change_memos_tag_id

  # def change_memos_tag_id
  #   memos.each { |memo| memo.update(tag_id: nil) }
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'タグを作成しました'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to @tag, notice: 'タグを更新しました'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag = Tag.find(params[:id])

    @tag.destroy
    redirect_to tags_url, notice: 'タグを削除しました'
  end

  private
    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_navbar.html.erb
<section id="nav">
  <div class="fixed-top ">
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <a class="navbar-brand" href="/">VitalizeMemoApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"> <%= link_to "タグ一覧", tags_path, class: 'nav-item nav-link active' %> </li>
        </ul>
      </div>
    </nav>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VitalizeMemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2>以下の入力に誤りがあります。</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-5">
    <div class=""><%= form.label :種類 %></div>
      <%= form.text_field :kind, class:"form-control"%>
    </div>
    <div class="float-right ">
      <div class="actions">
        <%= form.submit :"登録", class: 'btn btn-info'%>
        <%= link_to '戻る', tags_path, class: 'btn btn-info text-light' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h4 class="mt-4">Tag編集</h4>

<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<div class="alert alert-light" role="alert">
  <%= notice %>
</div>

<%= link_to 'タグ作成', new_tag_path,class:"btn btn-danger text-white mt-4" %>
<div class="contents d-flex flex-row flex-wrap w-">
  <% @tags.each do |tag| %>
    <div class="card mt-5 w-25 ml-5">
      <div class="card-body">
        <h3><span class="badge badge-pill badge-light"><%= tag.kind %></span></h3>
        <p class="h5 mt-2"></p>
        <div class="float-right">
          <%= link_to tag do %>
            <button type="submit" class="btn btn-info">詳細</button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tags/new.html.erb
<div class="container">
  <h4 class="mt-4">新規Tag</h4>
    <%= render 'form', tag: @tag %>
</div>

app/views/tags/show.html.erb
<div class="well well-lg">
  <h2 class="mt-4 mb-4">詳細ページ</h4>
  <div class="card">
    <div class="card-body">
      <p id="notice"><%= notice %></p>
      <p class="h6 mb-4">
        <strong>種類:</strong>
        <%= @tag.kind %>
      </p>
    </div>
  </div>
    <div class="button">
      <div class="float-right mt-1">
        <%= link_to edit_tag_path(@tag) do %>
          <button type="submit" class="btn btn-info">編集</button>
        <% end %>
        <%= link_to @tag, method: :delete do %>
          <button type="submit" class="btn btn-info">削除</button>
        <% end %>
      </div>
    </div>
</div>